emptyWriter: make it factory to be able to use it many times
Sage/f-streams pull request #21
Opened 2019-10-11 10:20 UTC by sberthier

emptyWriter was usable only once, so create a new one each time.
=> change interface but I guess it is not really used.

2019-10-23 12:05 UTC, bjouhier commented
@sberthier This is a breaking API change => increment major version. 

Another solution would be to introduce a new pair: empty.source(), empty.sink() or empty.createReader(), createWriter() (both functions) and deprecate the  old ones. I would prefer this.

2019-10-27 10:34 UTC, bjouhier requested changes
Good. Just doc and formatting glitches

2019-10-27 10:34 UTC, bjouhier commented on lib/ez.ts
> +/** @deprecated this writer is buggy, user createWriter instead */
```suggestion
/** @deprecated this writer is buggy, use emptySinkWriter() instead */
```

2019-10-27 10:34 UTC, bjouhier commented on lib/ez.ts
> +/** @deprecated */
```suggestion
/** @deprecated - use emptySourceReader() instead*/
```

2019-10-27 10:34 UTC, bjouhier commented on test/unit/ez-test.ts
> +        server = httpServer(function (req, res) {
```suggestion
        server = httpServer(function(req, res) {
```

2019-10-27 10:34 UTC, bjouhier commented on test/unit/ez-test.ts
> +                    function (prev, crt) {
```suggestion
                    function(prev, crt) {
```

2019-10-29 16:45 UTC, sberthier commented
I have fixed all your comments.

2019-10-30 15:37 UTC, bjouhier requested changes
I propose to change the name. I prefer createReader/Writer as verbal form is better than noun for functions. And also I prefer to stick to the reader/writer terminology which is used everywhere else.

Not sure the github _revision_ feature is the best way to do this but I started this way and decided to continue.

2019-11-08 09:03 UTC, sberthier commented
Sorry, I'm a bit late. I have applied your suggestions.

2022-03-04 13:13 UTC, bjouhier approved these changes

2022-03-04 13:14 UTC, merged

2022-03-04 13:15 UTC, bjouhier commented
@sberthier @tchambard Thanks a lot for the 4 PRs. I merged them and I'll republish to npm

2022-03-04 13:29 UTC, bjouhier commented
@sberthier @tchambard f-streams@3.2.0 is available. I bumped minor version because this PR adds new APIs.